version: '3.9'

volumes:
  nginx_log:
  hostbolg_logs:
  vueblog_assets:

configs:
  nginx_conf:
    file: ./env/nginx/nginx.conf

services:
   chat_web_host:
     container_name: chat_web_host
     image: registry.cn-hangzhou.aliyuncs.com/sdwyg/blogo:devhost
     restart: always
     networks:
       - calo-net
     volumes:
      - "hostbolg_logs:/app/App_Data/Logs"
     environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionString_Default=Server=120.26.216.57;Database=YChatDbTest;MultipleActiveResultSets=true;TrustServerCertificate=true;Uid=SA;Pwd=wyg154511LHL;
      - App__CorsOrigins=http://localhost:1545,http://localhost:5173,http://localhost:1545,http://120.26.216.57:1545
        App_RedisSetting_Connstr=124.71.15.19:6379,password=154511,defaultDatabase=1,ssl=false,writeBuffer=10240,poolsize=50,prefix=Y.Chat
    
   chat_web_ui:
     container_name: chat_web_ui
     image: registry.cn-hangzhou.aliyuncs.com/sdwyg/blogo:devui
     restart: always
     networks:
       -calo-net
     depends_on:
      - chat_web_host
     volumes:
      - vueblog_assets:/usr/share/nginx/html/assets


   nginx:
    image: nginx:1.16.1
    ports:
      - "1545:1545"
    networks:
      - calo_net
    volumes:
      - "nginx_log:/var/log/nginx"
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf



