version: '3.9'

services:
   chat_web_host:
     container_name: chat_web_host
     image: registry.cn-hangzhou.aliyuncs.com/sdwyg/blogo:devhost
     restart: always
     networks:
       - net
     deploy:
       replicas: 1
       placement:
         max_replicas_per_node: 1
       resources:
         limits:
           memory: 2048M
         reservations:
           memory: 512M
       restart_policy:
         condition: on-failure
         delay: 5s
         max_attempts: 5
       update_config:
         parallelism: 1
         delay: 10s
     environment:
    
   chat_web_ui:
     container_name: chat_web_ui
     image: registry.cn-hangzhou.aliyuncs.com/sdwyg/blogo:devui
     restart: always
     networks:
       - net
     deploy:
       replicas: 1
       placement:
         max_replicas_per_node: 1
       resources:
         limits:
         memory: 2048M
       reservations:
          memory: 512M
       restart_policy:
         condition: on-failure
         delay: 5s
         max_attempts: 5
       update_config:
         parallelism: 1
         delay: 10s
     depends_on:
      - chat_web_host
     environment:
      # -APPCONFIG=${CI_APPCONFIG_DEV}
   nginx:
    image: nginx:1.16.1
    ports:
      - "5100:5100"
      - "5200:5200"
      - "5155:5155"
    networks:
      - fantasy_net
    volumes:
      - "nginx_log:/var/log/nginx"
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf



