name: build_ci

on:
  push:
    branches: [wyg]
  pull_request:
    branches: [wyg]

jobs:
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: run docker compose
        run: |
            cd docker
            sudo docker-compose -f docker-compose.yml up -d
 