name: build_ci

on:
  push:
    branches: [wyg]
  pull_request:
    branches: [wyg]
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: run docker compose
        run: |
            sudo docker-compose -f ${{ secrets.DOCKERPOSEPATH }} up -d
 