name: build_ci

on:
  push:
    branches: [wyg]
  pull_request:
    branches: [wyg]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: login aliyun
        run: |
            sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hongkong.aliyuncs.com
      - name: Build Docker Image
        run: |
          image_name="chat-web-host"
          tag_name="devhost"
          if docker images | grep $image_name:$tag_name > /dev/null; then
           docker rmi $image_name:$tag_name
          fi
          cd src/aspnetcore/Y.ChatCore/Y.Chat.Host
          sudo docker build -t $image_name:$tag_name -f Dockerfile .

      - name: Build and push ALI
        id: ALI_build
        run: |
          image_name="chat-web-host"
          tag_name="devhost"
          sudo docker tag  $image_name:$tag_name registry.cn-hongkong.aliyuncs.com/sdwyg/blogo:$tag_name
          sudo docker push registry.cn-hongkong.aliyuncs.com/sdwyg/blogo:$tag_name

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: login aliyun
        run: |
            sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hongkong.aliyuncs.com
      - name: Build Docker Image
        run: |
          image_name="chat-web-ui"
          tag_name="devhost"
          if docker images | grep $image_name:$tag_name > /dev/null; then
           docker rmi $image_name:$tag_name
          fi
          cd src/web/Y.Chat.Web
          sudo docker build -t $image_name:$tag_name -f Dockerfile .

      - name: Build and push ALI
        id: ALI_build
        run: |
          image_name="chat-web-ui"
          tag_name="devhost"
          sudo docker tag  $image_name:$tag_name registry.cn-hongkong.aliyuncs.com/sdwyg/blogo:$tag_name
          sudo docker push registry.cn-hongkong.aliyuncs.com/sdwyg/blogo:$tag_name