name: build-cd

on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login aliyun
        run: |
            sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hongkong.aliyuncs.com       
      - name: run docker compose
        run: |
            ls -l
            cd docker
            sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hongkong.aliyuncs.com
            if  docker-compose -p chat_web_host ps > /dev/null 2>&1; then
              # 服务存在，停止并删除
              docker compose -f docker-compose.yml -p chat_web_host down
              echo "compose chat_web_host removed."
              sleep 10
            fi
            sudo docker compose -f docker-compose.yml -p chat_web_host pull && docker compose -f docker-compose.yml -p chat_web_host up -d
 